name: Register
version: 0.1
main: 
description: This is an implementation of Nijikokun's Register designed for easy implementation by LRFLEW
author: Nijikokun
website: http://forums.bukkit.org/threads/16849/
softdepend: [iConomy, BOSEconomy, Currency]